export interface TicketDefinition {
  id: string;
  title: string;
  system: "gridlock-scraper";
  objective: string;
  scopeFiles: string[];
  acceptanceCriteria: string[];
  testFile: string;
  expectedStatus: "Done" | "In Progress" | "Todo";
}

export const SCRAPER_TICKETS: TicketDefinition[] = [
  {
    id: "01",
    title: "Ticket 01: Scaffold gridlock-scraper Repository & Drizzle Schema",
    system: "gridlock-scraper",
    objective: "Scaffold gridlock-scraper repository with Node.js >= 22, TypeScript, Drizzle ORM, SQLite.",
    scopeFiles: ["src/schema.ts", "package.json", "tsconfig.json"],
    acceptanceCriteria: [
      "Drizzle ORM schema defined with source_artifacts, observations, projections, connector_configs, repair_audits",
      "In-memory SQLite initialization and migrations execute cleanly",
      "Node.js >= 22 and TypeScript configuration enforced",
      "Type definitions export strictly typed entities without raw SQL",
    ],
    testFile: "tests/tickets/ticket-01.test.ts",
    expectedStatus: "Done",
  },
  {
    id: "02",
    title: "Ticket 02: Immutable Raw Artifact Store",
    system: "gridlock-scraper",
    objective: "Build Gzip compression and SHA-256 cryptographic hashing pipeline for raw HTML, JSON, and PDF payloads.",
    scopeFiles: ["src/storage/artifact-store.ts", "src/schema.ts"],
    acceptanceCriteria: [
      "Payloads compressed with gzip; SHA-256 hash verified against uncompressed stream",
      "Duplicate payload ingest returns existing artifact record without re-uploading",
      "Metadata recorded in source_artifacts table",
    ],
    testFile: "tests/tickets/ticket-02.test.ts",
    expectedStatus: "Done",
  },
  {
    id: "03",
    title: "Ticket 03: TDLR TABS Construction Filings Connector",
    system: "gridlock-scraper",
    objective: "Implement deterministic HTML extractor and pure parser for Texas Department of Licensing and Regulation (TDLR) TABS records.",
    scopeFiles: ["src/extractors/tdlr.ts", "src/parsers/tdlr.ts", "src/schemas/tdlr.ts"],
    acceptanceCriteria: [
      "Extracts project number, estimated cost, square footage, address, county, owner, and architect",
      "Validates extracted records against Zod TdlrRecordSchema",
      "Emits atomic observations rows linked to captured source_artifact_id",
    ],
    testFile: "tests/tickets/ticket-03.test.ts",
    expectedStatus: "Done",
  },
  {
    id: "04",
    title: "Ticket 04: City of Austin Permitting (AB+C / Socrata) Connector",
    system: "gridlock-scraper",
    objective: "Implement Austin Open Data Socrata API and AB+C portal commercial building permit extractor.",
    scopeFiles: ["src/connectors/austin-permits.ts", "src/schemas/austin.ts"],
    acceptanceCriteria: [
      "Queries Socrata endpoint with incremental date bounds",
      "Extracts permit number, status, valuation, applicant, and GIS parcel ID",
      "Handles 429 rate limiting with exponential backoff and jitter",
    ],
    testFile: "tests/tickets/ticket-04.test.ts",
    expectedStatus: "Done",
  },
  {
    id: "05",
    title: "Ticket 05: TCEQ Permits & ERCOT Large-Load Queue Connectors",
    system: "gridlock-scraper",
    objective: "Build parsers for Texas Commission on Environmental Quality (air/water permits) and ERCOT interconnection spreadsheets.",
    scopeFiles: ["src/parsers/tceq.ts", "src/parsers/ercot.ts", "src/schemas/tceq.ts", "src/schemas/ercot.ts"],
    acceptanceCriteria: [
      "Ingests Excel (.xlsx) or CSV ERCOT queue data into structured load records (MW, county, substation tie-in)",
      "Extracts TCEQ air quality permits for backup diesel generator clusters",
      "Flags projects matching large load or data center queue thresholds",
    ],
    testFile: "tests/tickets/ticket-05.test.ts",
    expectedStatus: "Done",
  },
  {
    id: "06",
    title: "Ticket 06: Out-of-Band Gemini Flash Repair Agent & Replay Sandbox",
    system: "gridlock-scraper",
    objective: "Build anomaly detection guard and sandboxed LLM repair agent for broken selectors.",
    scopeFiles: ["src/repair/replay.ts", "src/repair/quarantine.ts", "src/jobs/runner.ts"],
    acceptanceCriteria: [
      "Flags volume drop or missing required fields as anomaly",
      "Synthesizes candidate patch against isolated replay harness",
      "Executes patch against historical fixture files in sandboxed runner",
      "Only promotes patch to connector_configs.manifest if replay pass rate is 100%",
    ],
    testFile: "tests/tickets/ticket-06.test.ts",
    expectedStatus: "In Progress",
  },
  {
    id: "07",
    title: "Ticket 07: Scraper HTTP API & Source Health Exporter",
    system: "gridlock-scraper",
    objective: "Expose worker HTTP endpoints for triggering ingestion runs, querying status, and streaming telemetry.",
    scopeFiles: ["src/server.ts", "src/routes/health.ts"],
    acceptanceCriteria: [
      "POST /api/ingest/trigger dispatches asynchronous connector runs",
      "GET /api/ingest/status returns run metrics and invariant state",
      "GET /api/source-health/telemetry reports connector uptime and repair audits",
    ],
    testFile: "tests/tickets/ticket-07.test.ts",
    expectedStatus: "Todo",
  },
  {
    id: "19",
    title: "Ticket 19: Containerize gridlock-scraper with Playwright Base",
    system: "gridlock-scraper",
    objective: "Package the scraper into a secure, reproducible Linux container using Microsoft's official Playwright base image.",
    scopeFiles: ["Dockerfile", ".dockerignore", "package.json"],
    acceptanceCriteria: [
      "Multi-stage Dockerfile based on mcr.microsoft.com/playwright:v1.63.0-noble",
      "Installs Node.js >= 22 dependencies via npm ci and runs npm run build",
      "Drops root privileges to run as unprivileged pwuser",
      "Image compiles and verifies offline tests cleanly inside container",
    ],
    testFile: "tests/tickets/ticket-19.test.ts",
    expectedStatus: "Todo",
  },
  {
    id: "20",
    title: "Ticket 20: Ingestion CLI Entrypoint & Process Exit Protocol",
    system: "gridlock-scraper",
    objective: "Implement a command-line entrypoint with source filtering and deterministic process exit codes for orchestrators.",
    scopeFiles: ["src/cli.ts", "package.json"],
    acceptanceCriteria: [
      "CLI parses arguments: --source=<tdlr|ercot|tceq|municipal|all>, --dry-run, --force",
      "Exits with code 0 on clean completion or content-hash early exit",
      "Exits with code 1 on uncaught network/runtime crashes",
      "Exits with code 2 when an invariant breach or anomaly is quarantined (notifies external monitoring)",
      "Unit tests verify argument parsing and exit code mapping",
    ],
    testFile: "tests/tickets/ticket-20.test.ts",
    expectedStatus: "Todo",
  },
  {
    id: "21",
    title: "Ticket 21: Cloudflare R2 State Hydration & Snapshot Publishing Hooks",
    system: "gridlock-scraper",
    objective: "Build pre-run hydration and post-run sync scripts to pull and push gridlock.db, raw .artifacts/, and dist/exports/*.json to S3/R2 storage.",
    scopeFiles: ["scripts/sync-state.ts", "package.json"],
    acceptanceCriteria: [
      "Pre-run pulls existing gridlock.db and SHA-256 hash manifest from Cloudflare R2 (falls back to fresh schema if empty)",
      "Post-run pushes mutated gridlock.db atomically (upload to .tmp key then move)",
      "Syncs new content-addressable raw payload blobs to R2 bucket",
      "Verifies payload SHA-256 checksums before and after upload",
    ],
    testFile: "tests/tickets/ticket-21.test.ts",
    expectedStatus: "Todo",
  },
  {
    id: "22",
    title: "Ticket 22: Scheduled Ingestion Workflow & Anomaly Webhook Alerts",
    system: "gridlock-scraper",
    objective: "Configure scheduled CI/CD runner execution with automated secret binding and anomaly alerting.",
    scopeFiles: [".github/workflows/ingest.yml", "scripts/notify-anomaly.ts"],
    acceptanceCriteria: [
      "GitHub Actions workflow triggers every 6 hours (cron: '0 */6 * * *') and supports workflow_dispatch",
      "Runs pre-sync -> CLI ingestion sweep -> post-sync sequentially",
      "Binds repository secrets: CLOUDFLARE_R2_*, GEMINI_API_KEY, ALERT_WEBHOOK_URL",
      "Dispatches webhook alert (Discord/Slack) if CLI exits with code 2 (anomaly quarantined)",
    ],
    testFile: "tests/tickets/ticket-22.test.ts",
    expectedStatus: "Todo",
  },
  {
    id: "23",
    title: "Ticket 23: Playwright Download Lifecycle for ERCOT Interconnection Queue",
    system: "gridlock-scraper",
    objective: "Intercept and download linked XLSX/CSV spreadsheet payloads during ERCOT queue extraction instead of capturing portal HTML.",
    scopeFiles: ["src/extractors/ercot.ts"],
    acceptanceCriteria: [
      "Implement Playwright download listener (page.waitForEvent('download')) to capture linked ERCOT GIS report spreadsheet",
      "Set accurate extraction content type (text/csv or Excel MIME type)",
      "Pipe downloaded binary buffer to raw extraction result content",
      "Fall back gracefully or raise extraction anomaly on network timeout",
    ],
    testFile: "tests/tickets/ticket-23.test.ts",
    expectedStatus: "Done",
  },
  {
    id: "24",
    title: "Ticket 24: Replay Audit Approval Gate for Quarantine Reprocessing",
    system: "gridlock-scraper",
    objective: "Gate quarantine payload release on verified out-of-band promotion, requiring a verified repair_audits record before re-evaluating and promoting a quarantined artifact.",
    scopeFiles: ["src/jobs/runner.ts", "src/storage/db.ts"],
    acceptanceCriteria: [
      "Query repair_audits for connector status promoted before attempting quarantine re-ingestion",
      "Unreviewed parser runs leave failing payload in quarantine without false anomaly clearing",
      "Reprocessing requires verified promotion proof",
    ],
    testFile: "tests/tickets/ticket-24.test.ts",
    expectedStatus: "Done",
  },
  {
    id: "25",
    title: "Ticket 25: Patch Manifest Persistence on Promoted Replay Verification",
    system: "gridlock-scraper",
    objective: "Persist candidate patch descriptions (proposedPatchDescription) into connector_configs.manifest atomically upon successful replay verification.",
    scopeFiles: ["src/repair/replay.ts", "src/storage/db.ts"],
    acceptanceCriteria: [
      "When evaluateCandidatePatch passes 100%, update connector_configs.manifest with the proposed patch",
      "Atomically commit audit record, manifest update, and connector status ok",
      "Subsequent scraper executions load updated selectors from connector_configs.manifest",
    ],
    testFile: "tests/tickets/ticket-25.test.ts",
    expectedStatus: "Done",
  },
  {
    id: "26",
    title: "Ticket 26: Mandatory Semantic Oracles for Replay Fixture Evaluation",
    system: "gridlock-scraper",
    objective: "Require semantic assertions (expectedMinCount or expectedSubjectIds or expectedAssertion) on all ReplayFixture instances, prohibiting expectation-free fixture promotion.",
    scopeFiles: ["src/repair/replay.ts"],
    acceptanceCriteria: [
      "Enforce in TypeScript and runtime that ReplayFixture must provide at least one semantic oracle",
      "Reject any fixture evaluation where no semantic oracle is specified",
      "Update all pipeline and repair tests to provide explicit expected counts and IDs",
    ],
    testFile: "tests/tickets/ticket-26.test.ts",
    expectedStatus: "Done",
  },
  {
    id: "27",
    title: "Ticket 27: Strict Municipal Docket Status Validation",
    system: "gridlock-scraper",
    objective: "Eliminate synthetic fallback to 'under_review' when .action-status is missing or contains unsupported values, failing validation to trigger anomaly quarantine.",
    scopeFiles: ["src/parsers/municipal.ts", "src/schemas/municipal.ts"],
    acceptanceCriteria: [
      "Remove || 'under_review' fallback from parseMunicipalAgenda",
      "Missing or unmapped status values pass raw or undefined to validateMunicipalInvariants",
      "Zod schema rejects invalid statuses, triggering quarantine isolation on selector drift",
    ],
    testFile: "tests/tickets/ticket-27.test.ts",
    expectedStatus: "Done",
  },
  {
    id: "28",
    title: "Ticket 28: Dynamic Municipal Action Type Classification",
    system: "gridlock-scraper",
    objective: "Extract and derive the actual municipal action type (zoning, annexation, site_plan, building_permit, hearing, variance) from agenda docket items rather than hardcoding 'zoning'.",
    scopeFiles: ["src/parsers/municipal.ts", "src/schemas/municipal.ts"],
    acceptanceCriteria: [
      "Extract explicit .action-type element or classify from title/body regex",
      "Map into validated MunicipalActionType enum in src/schemas/municipal.ts",
      "Fail validation on unclassifiable or missing action types",
    ],
    testFile: "tests/tickets/ticket-28.test.ts",
    expectedStatus: "Done",
  },
  {
    id: "29",
    title: "Ticket 29: Quarantine Media Type & Storage Extension Preservation",
    system: "gridlock-scraper",
    objective: "Preserve the actual contentType and file extension of failing payloads during quarantine instead of hardcoding text/html.",
    scopeFiles: ["src/repair/quarantine.ts", "src/jobs/runner.ts"],
    acceptanceCriteria: [
      "Pass contentType and deducted file extension into quarantineExtractionFailure",
      "Store CSV/PDF/JSON payloads under their canonical format in ArtifactStore and source_artifacts",
      "Accurate provenance metadata recorded for downstream replay tooling",
    ],
    testFile: "tests/tickets/ticket-29.test.ts",
    expectedStatus: "Done",
  },
];
